"""Shared constants: status values, block types, error codes and severities.

Plain string constants are used (rather than Enum) because they are stored
verbatim in SQLite and exported to Excel.
"""

from __future__ import annotations

from maintdoc import __version__

TOOL_NAME = "maintdoc"
TOOL_VERSION = __version__
# Bump when extraction output could change for the same input and settings.
# A change forces re-extraction of otherwise unchanged sources.
EXTRACTOR_VERSION = "1.0"

DRAFT_DISCLAIMER = (
    "DRAFT - generated by deterministic rule-based automation from source PDFs. "
    "This document is NOT released for use. All content must pass qualified "
    "engineering review and formal release before it is used for maintenance work. "
    "Rule-based extraction does not establish semantic completeness or safety certification."
)


class SourceStatus:
    """Inventory / integrity status of a discovered PDF file."""

    OK = "ok"
    OFFLINE_PLACEHOLDER = "offline_placeholder"
    CORRUPT = "corrupt"
    ENCRYPTED = "encrypted"
    EMPTY_DOCUMENT = "empty_document"
    UNREADABLE = "unreadable"
    DUPLICATE = "duplicate"
    MISSING = "missing"

    ALL = (OK, OFFLINE_PLACEHOLDER, CORRUPT, ENCRYPTED, EMPTY_DOCUMENT, UNREADABLE, DUPLICATE, MISSING)


class ExtractionStatus:
    """Extraction status of a source document."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETE = "complete"
    COMPLETE_WITH_ERRORS = "complete_with_errors"
    FAILED = "failed"
    NOT_APPLICABLE = "not_applicable"  # corrupt, encrypted, placeholder, missing
    SKIPPED_DUPLICATE = "skipped_duplicate"

    FINAL = (COMPLETE, COMPLETE_WITH_ERRORS, FAILED, NOT_APPLICABLE, SKIPPED_DUPLICATE)
    DONE_OK = (COMPLETE, COMPLETE_WITH_ERRORS)


class PageStatus:
    """Extraction status of an individual PDF page. Every page receives one."""

    OK = "ok"                              # native text extracted
    OK_OCR = "ok_ocr"                      # OCR text extracted, acceptable confidence
    OK_MIXED = "ok_mixed"                  # native text + OCR of embedded images
    OCR_LOW_CONFIDENCE = "ocr_low_confidence"
    OCR_UNAVAILABLE = "ocr_unavailable"    # OCR needed but Tesseract not available / disabled
    OCR_FAILED = "ocr_failed"
    LOW_QUALITY_TEXT = "low_quality_text"  # gibberish native text, no OCR replacement
    GRAPHIC_ONLY = "graphic_only"          # drawings/images but no text (visual check needed)
    EMPTY = "empty"
    BLANK_INTENTIONAL = "blank_intentional"
    FAILED = "failed"

    ALL = (OK, OK_OCR, OK_MIXED, OCR_LOW_CONFIDENCE, OCR_UNAVAILABLE, OCR_FAILED,
           LOW_QUALITY_TEXT, GRAPHIC_ONLY, EMPTY, BLANK_INTENTIONAL, FAILED)
    PROBLEM = (OCR_LOW_CONFIDENCE, OCR_UNAVAILABLE, OCR_FAILED, LOW_QUALITY_TEXT, EMPTY, FAILED)


class BlockType:
    HEADING = "heading"
    PARAGRAPH = "paragraph"
    LIST_ITEM = "list_item"
    TABLE = "table"
    DANGER = "danger"
    WARNING = "warning"
    CAUTION = "caution"
    NOTICE = "notice"
    NOTE = "note"
    CAPTION = "caption"
    FIGURE = "figure"
    HEADER_FOOTER = "header_footer"
    TABLE_TEXT = "table_text"   # native text that lies inside an extracted table
    FIGURE_TEXT = "figure_text"  # labels inside a figure region (kept, rendered with the figure)

    SAFETY = (DANGER, WARNING, CAUTION, NOTICE)
    ADMONITIONS = (DANGER, WARNING, CAUTION, NOTICE, NOTE)
    STATEMENT_TYPES = (PARAGRAPH, LIST_ITEM, TABLE, DANGER, WARNING, CAUTION, NOTICE, NOTE,
                       CAPTION, FIGURE)
    DEDUPE_TYPES = (PARAGRAPH, LIST_ITEM, TABLE, DANGER, WARNING, CAUTION, NOTICE, NOTE, CAPTION)


class EvidenceStatus:
    ACTIVE = "active"
    EXCLUDED = "excluded"      # kept for traceability, excluded at extraction (e.g. duplicate text layer)
    SUPERSEDED = "superseded"  # source changed or re-extracted; never deleted


class ExtractionMethod:
    PYMUPDF_TEXT = "pymupdf_text"
    PDFPLUMBER_TABLE = "pdfplumber_table"
    PYMUPDF_TABLE = "pymupdf_table"
    TESSERACT_OCR = "tesseract_ocr"
    PYMUPDF_IMAGE = "pymupdf_image"
    PYMUPDF_DRAWING = "pymupdf_drawing"


class ReviewStatus:
    UNREVIEWED = "unreviewed"
    APPROVED = "approved"
    REJECTED = "rejected"
    NEEDS_REVISION = "needs_revision"
    INVALIDATED = "invalidated"

    ALL = (UNREVIEWED, APPROVED, REJECTED, NEEDS_REVISION, INVALIDATED)


class ConflictStatus:
    OPEN = "open"
    RESOLVED = "resolved"
    NOT_A_CONFLICT = "not_a_conflict"
    STALE = "stale"          # evidence superseded; re-detected on next validate if still present

    UNRESOLVED = (OPEN,)


class Severity:
    CRITICAL = "critical"
    MAJOR = "major"
    MINOR = "minor"
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"

    RANK = {CRITICAL: 0, ERROR: 1, MAJOR: 1, WARNING: 2, MINOR: 2, INFO: 3}


class ErrorStatus:
    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    WONT_FIX = "wont_fix"
    SUPERSEDED = "superseded"

    CLOSED = (RESOLVED, WONT_FIX, SUPERSEDED)


class VisualCheckStatus:
    PENDING = "pending"
    PASSED = "passed"
    FAILED = "failed"
    INVALIDATED = "invalidated"


# Error register codes: code -> (default severity, description)
ERROR_CODES: dict[str, tuple[str, str]] = {
    "OFFLINE_PLACEHOLDER": (Severity.ERROR, "OneDrive online-only placeholder; file content not available locally"),
    "FILE_UNREADABLE": (Severity.ERROR, "File could not be read (permissions, lock or I/O error)"),
    "NOT_A_PDF": (Severity.ERROR, "File does not start with a PDF header"),
    "CORRUPT_PDF": (Severity.CRITICAL, "PDF could not be opened or parsed"),
    "PDF_REPAIRED": (Severity.WARNING, "PDF structure was damaged and repaired on open; verify content visually"),
    "PDF_NO_EOF": (Severity.WARNING, "PDF end-of-file marker missing (possibly truncated)"),
    "ENCRYPTED_PDF": (Severity.ERROR, "PDF is password protected; content cannot be extracted"),
    "EMPTY_DOCUMENT": (Severity.ERROR, "PDF contains no pages"),
    "PAGE_LOAD_FAILED": (Severity.ERROR, "Page could not be loaded"),
    "PAGE_EXTRACTION_FAILED": (Severity.ERROR, "Unexpected failure while extracting a page"),
    "EMPTY_PAGE": (Severity.WARNING, "Page has no extractable text, images or drawings"),
    "GRAPHIC_ONLY_PAGE": (Severity.WARNING, "Page contains graphics but no text; human visual check required"),
    "OCR_UNAVAILABLE": (Severity.CRITICAL, "Page requires OCR but Tesseract is unavailable or disabled"),
    "OCR_FAILED": (Severity.ERROR, "OCR failed on page"),
    "OCR_LOW_CONFIDENCE": (Severity.ERROR, "OCR page confidence below threshold"),
    "OCR_LOW_CONFIDENCE_BLOCK": (Severity.WARNING, "OCR text block confidence below threshold"),
    "OCR_NO_TEXT": (Severity.WARNING, "OCR produced no text for a page that needed OCR"),
    "TABLE_EXTRACTION_FAILED": (Severity.ERROR, "Table extraction failed; text kept as plain blocks"),
    "TABLE_DETECTION_SKIPPED": (Severity.WARNING, "Table detection skipped on a very complex page"),
    "TABLE_IRREGULAR": (Severity.WARNING, "Table has irregular structure (empty/merged cells); visual check required"),
    "GIBBERISH_TEXT": (Severity.WARNING, "Extracted text looks like gibberish (encoding/font problem)"),
    "LOW_QUALITY_PAGE_TEXT": (Severity.ERROR, "Native page text is low quality and could not be replaced by OCR"),
    "FIGURE_RENDER_FAILED": (Severity.WARNING, "Figure region could not be rendered to an image"),
    "MISSING_METADATA": (Severity.WARNING, "Document metadata field could not be determined"),
    "AMBIGUOUS_METADATA": (Severity.WARNING, "Several conflicting values found for a metadata field"),
    "UNCLASSIFIED_STATEMENT": (Severity.WARNING, "Statement could not be assigned to a manual chapter"),
    "AMBIGUOUS_CLASSIFICATION": (Severity.INFO, "Statement matched several chapters with similar scores"),
    "UNIT_MISSING": (Severity.WARNING, "Numeric value in a technical context has no unit"),
    "UNIT_DIMENSION_MISMATCH": (Severity.ERROR, "Unit dimensionality does not match the parameter context"),
    "UNIT_AMBIGUOUS": (Severity.WARNING, "Unit or number format is ambiguous; conversion flagged unsafe"),
    "UNIT_UNKNOWN": (Severity.WARNING, "Unit could not be interpreted"),
    "DUAL_UNIT_INCONSISTENT": (Severity.ERROR, "Value given in two units that do not agree"),
    "GENERATION_ERROR": (Severity.ERROR, "Error while generating a manual"),
    "GENERATION_UNCITED_ITEM": (Severity.CRITICAL, "Generated item had no citation and was withheld"),
    "SOURCE_CHANGED": (Severity.WARNING, "Source file content changed; dependent approvals invalidated"),
    "SOURCE_MISSING": (Severity.WARNING, "Previously registered source file is no longer present"),
}

# Manual chapters that are always generated (ids must match config classification.chapters)
UNCLASSIFIED_CHAPTER = "unclassified"
